
"use client";

import Image from "next/image";
import { Button } from "./ui/button";
import { Download, Share2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

type GeneratedImageCardProps = {
    imageDataUri: string;
    prompt: string;
};

export function GeneratedImageCard({ imageDataUri, prompt }: GeneratedImageCardProps) {
    const { toast } = useToast();

    const handleDownload = () => {
        const link = document.createElement('a');
        link.href = imageDataUri;
        link.download = `${prompt.substring(0, 20).replace(/\s+/g, '_')}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        toast({ title: "Image downloaded!" });
    };

    const handleShare = () => {
        if (navigator.share) {
            fetch(imageDataUri)
                .then(res => res.blob())
                .then(blob => {
                    const file = new File([blob], 'generated_image.png', { type: 'image/png' });
                    navigator.share({
                        title: 'Image from SearnAI',
                        text: `Image generated from prompt: "${prompt}"`,
                        files: [file],
                    }).catch(error => console.log('Error sharing', error));
                });
        } else {
            navigator.clipboard.writeText(imageDataUri);
            toast({ title: "Copied!", description: "Image data URL copied to clipboard." });
        }
    };

    return (
        <div className="w-full max-w-[200px] rounded-none border border-foreground/20 bg-background overflow-hidden shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] dark:shadow-[3px_3px_0px_0px_rgba(255,255,255,1)]">
            <div className="relative aspect-square">
                <Image
                    src={imageDataUri}
                    alt={prompt}
                    fill
                    sizes="200px"
                    className="object-cover"
                />
            </div>
            <div className="p-2">
                <span className="font-bold text-xs line-clamp-2 uppercase tracking-tight block">{prompt}</span>
                <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest mt-0.5 block">Generated by Imagen</span>
                <div className="mt-2 flex gap-1.5">
                    <Button
                        variant="outline"
                        size="sm"
                        className="w-full rounded-none border-foreground/20 font-bold uppercase text-xs tracking-widest hover:bg-foreground hover:text-background transition-colors"
                        onClick={handleDownload}
                    >
                        <Download className="mr-2 h-4 w-4" />
                        Download
                    </Button>
                    <Button
                        variant="outline"
                        size="icon"
                        className="rounded-none border-foreground/20 hover:bg-foreground hover:text-background transition-colors"
                        onClick={handleShare}
                    >
                        <Share2 className="h-4 w-4" />
                    </Button>
                </div>
            </div>
        </div>
    );
}
